<?xml version="1.0" encoding="utf-8"?><Database Name="Hospital Database" Class="Hospital_DatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=&quot;|DataDirectory|\Hospital Database.mdf&quot;;Integrated Security=True;Connect Timeout=30" SettingsObjectName="Doctor_s_Portal.Properties.Settings" SettingsPropertyName="Hospital_DatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[Disease List]" Member="Disease_Lists">
    <Type Name="Disease_List">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.[Medicine List]" Member="Medicine_Lists">
    <Type Name="Medicine_List">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Manufacturer" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[Retail Price(Tk.)]" Member="Retail_Price_Tk__" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.[Symptom List]" Member="Symptom_Lists">
    <Type Name="Symptom_List">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.[Test List]" Member="Test_Lists">
    <Type Name="Test_List">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.[Doctor's List]" Member="Doctor_s_Lists">
    <Type Name="Doctor_s_List">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[Date Of Birth]" Member="Date_Of_Birth" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="[Date Joined]" Member="Date_Joined" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Designation" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Specialty" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Image" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="[Mobile No.]" Member="Mobile_No_" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.[Patient Report]" Member="Patient_Reports">
    <Type Name="Patient_Report">
      <Column Name="Contact" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[Report Date]" Member="Report_Date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Prescription" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Patient_Info_Patient_Report" Member="Patient_Info" ThisKey="Contact" OtherKey="Contact" Type="Patient_Info" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Patient_Info" Member="Patient_Infos">
    <Type Name="Patient_Info">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Age" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Blood Group]" Member="Blood_Group" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Contact" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Patient_Info_Patient_Report" Member="Patient_Reports" ThisKey="Contact" OtherKey="Contact" Type="Patient_Report" />
    </Type>
  </Table>
</Database>